### ISSUE TITLE
claims no installs but `msvcrt` and `getch` are not found

### ISSUE THREAD

**Issue by xguse** [BlitzKraft/vimDDR#2]
Here is what I have done:

```
gus at r45012 in ~/src/repos/git
$ git clone https://github.com/BlitzKraft/vimDDR.git
Cloning into 'vimDDR'...
remote: Counting objects: 118, done.
remote: Compressing objects: 100% (13/13), done.
remote: Total 118 (delta 1), reused 0 (delta 0), pack-reused 101
Receiving objects: 100% (118/118), 42.45 KiB | 0 bytes/s, done.
Resolving deltas: 100% (39/39), done.

(none)
gus at r45012 in ~/src/repos/git
$ cd vimDDR

(none)
gus at r45012 in ~/src/repos/git/vimDDR (master)
$ ll
total 40K
-rwxr-xr-x 1 gus users 2.6K Nov 17 09:17 game.py
-rw-r--r-- 1 gus users 1.6K Nov 17 09:17 README.md
-rw-r--r-- 1 gus users   97 Nov 17 09:17 scores.txt
-rw-r--r-- 1 gus users  28K Nov 17 09:17 screenshot.png

(none)
gus at r45012 in ~/src/repos/git/vimDDR (master)
$ ./game.py
Traceback (most recent call last):
  File "./game.py", line 12, in <module>
    import msvcrt
ImportError: No module named 'msvcrt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./game.py", line 14, in <module>
    import getch
ImportError: No module named 'getch'
```

**Comment by xguse** [comment]
I see that you DO list these in the 'dependency' section which I did not see before.  However, I think your wording is a little ambiguous. What I think you mean by no install is that i dont have to add this code to my local python environment? I might actually call this a disadvantage because I have to manage dependencies manually. Having a `setup.py` would allow this to me handled for the user at install time. IMO, most folks used to python will expect this.

Gus

**Comment by xguse** [comment]
im back! Sorry.  But even after installing `getch`, I am getting the same traceback.  The problem seems to be that you have not discovered `#!/usr/bin/env python`.

MANY people maintain multiple python environments, each with their own set of installed packages.  This makes development MUCH easier as you progress and also keeps you from tampering with system python environments which can screw up your system if you are careless.

`#!/usr/bin/env python` says: hey system? use whichever python `which python` returns to run this file.

I have submitted this change as a PR.

Gus

**Comment by BlitzKraft** [comment]
That is right. Merged.

Edit: When I mentioned no install required, I meant that this can run as a standalone script. I am working on creating a pypi package. Development is ongoing in the branch 'pypi'.
